# Generated by Django 3.0.3 on 2020-07-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_register_number', models.IntegerField()),
                ('student_name', models.CharField(max_length=50)),
                ('birthday', models.DateField(auto_now=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('caste', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_date', models.DateField(auto_now=True)),
                ('standard', models.IntegerField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')])),
                ('division', models.CharField(blank=True, choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd')], max_length=50, null=True)),
            ],
        ),
    ]
