# Generated by Django 3.0.3 on 2020-07-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birthday',
            new_name='birthdate',
        ),
    ]
